"""Add User model

Revision ID: 35eb189cbbbb
Revises: 53097d322cf3
Create Date: 2025-07-08 11:13:09.470246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35eb189cbbbb'
down_revision = '53097d322cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('SUPER_USER', 'ADMIN', 'GURU', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
