"""Add jawaban_siswa table

Revision ID: 53097d322cf3
Revises: 915928f11cf8
Create Date: 2025-07-08 11:08:39.448644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53097d322cf3'
down_revision = '915928f11cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('tanggal_ujian', sa.DateTime(), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jawaban_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jawaban_teks', sa.Text(), nullable=True),
    sa.Column('skor', sa.Float(), nullable=True),
    sa.Column('ujian_id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['ujian_id'], ['ujian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jawaban_siswa')
    op.drop_table('ujian')
    # ### end Alembic commands ###
