"""Initial database setup

Revision ID: 75902d50f365
Revises: 
Create Date: 2025-07-09 00:01:00.430602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75902d50f365'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=100), nullable=False),
    sa.Column('jenjang', sa.String(length=50), nullable=False),
    sa.Column('mata_pelajaran', sa.String(length=100), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('nis', sa.String(length=20), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=True),
    sa.Column('agama', sa.String(length=50), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nomor_hp', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('SUPER_USER', 'ADMIN', 'GURU', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelas_siswa',
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('kelas_id', 'siswa_id')
    )
    op.create_table('rpp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('konten_markdown', sa.Text(), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('konten_json', sa.Text(), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('rpp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpp_id'], ['rpp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('tanggal_ujian', sa.DateTime(), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['soal_id'], ['soal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jawaban_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jawaban_teks', sa.Text(), nullable=True),
    sa.Column('skor', sa.Float(), nullable=True),
    sa.Column('ujian_id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.ForeignKeyConstraint(['ujian_id'], ['ujian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jawaban_siswa')
    op.drop_table('ujian')
    op.drop_table('soal')
    op.drop_table('rpp')
    op.drop_table('kelas_siswa')
    op.drop_table('absensi')
    op.drop_table('user')
    op.drop_table('siswa')
    op.drop_table('kelas')
    # ### end Alembic commands ###
