"""Membuat tabel Soal

Revision ID: 915928f11cf8
Revises: c56156e176b4
Create Date: 2025-07-06 23:56:20.958040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915928f11cf8'
down_revision = 'c56156e176b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('konten_json', sa.Text(), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('rpp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpp_id'], ['rpp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soal')
    # ### end Alembic commands ###
