"""Membuat semua tabel awal dengan constraint name

Revision ID: 96fd0f8c2f80
Revises: 
Create Date: 2025-07-06 21:35:56.858538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fd0f8c2f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=100), nullable=False),
    sa.Column('jenjang', sa.String(length=50), nullable=False),
    sa.Column('mata_pelajaran', sa.String(length=100), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('nis', sa.String(length=20), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=True),
    sa.Column('agama', sa.String(length=50), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nomor_hp', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nisn')
    )
    op.create_table('absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelas_siswa',
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('kelas_id', 'siswa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelas_siswa')
    op.drop_table('absensi')
    op.drop_table('siswa')
    op.drop_table('kelas')
    # ### end Alembic commands ###
