"""Membuat tabel RPP

Revision ID: c56156e176b4
Revises: 96fd0f8c2f80
Create Date: 2025-07-06 23:29:21.296494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56156e176b4'
down_revision = '96fd0f8c2f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('konten_markdown', sa.Text(), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpp')
    # ### end Alembic commands ###
